### ISSUE TITLE
Installer: allow different installation directories 

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rustup.rs#1904]
can i use `/usr/local/bin` for rust tool-chain installation?

**Comment by rbtcollins** [comment]
Yes - you can install the toolchains manually yourself in any root path you desire.

rustup itself doesn't install globally - it is a per-user multiple-tool-chain multiplexing system : it installs all the toolchains it installs off-path and uses proxies to instantiate the desired toolchain binaries as requested.

I'm closing this as it seems like purely an information request.
