### ISSUE TITLE
Install ends with `error: toolchain 'stable' not installed`

### ISSUE THREAD

**Issue by brson** [rust-lang/rustup.rs#277]
[Source](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/58?u=brson).

```


    [...]

    WARNING: This is an early beta. Expect breakage.

    Continue? (Y/n) y

    error: toolchain 'stable' is not installed
```

**Comment by jarod** [comment]
```
$ ./rustup-setup --version
multirust-setup 0.1.4

$ ./rustup-setup --verbose --default-toolchain stable

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

It will add the `cargo`, `rustc`, `rustup` and other commands to
Cargo's bin directory, located at:

/home/jarod/.cargo/bin

This path will then be added to your `PATH` environment variable by
modifying the shell startup files located at:

/home/jarod/.bashrc
/home/jarod/.zshrc

You can uninstall at any time with `rustup self uninstall` and
these changes will be reverted.

WARNING: This is an early beta. Expect breakage.

Continue? (Y/n) 

error: toolchain 'stable' is not installed
```

**Comment by nodakai** [comment]
When I got this error, I removed existing `C:\Users\nodakai\.cargo` and `C:\Users\nodakai\.multirust` from an old version, ran `rustup-setup.exe` again and then got everything right.

**Comment by azerupi** [comment]
Indeed, just removing `~/.multirust` solved this issue

**Comment by chriskrycho** [comment]
Maybe add an option to remove existing `.multirust` and/or `.cargo` directories and continue?

**Comment by brson** [comment]
Yeah, I need to buckle down and write some compatibility code to handle multirust.sh -> rustup upgrades.

Probably what @chriskrycho suggests is best, just detect the old directories, and offer to either remove them or cancel before proceeding.

**Comment by kamalmarhubi** [comment]
If removing these directories, try to preserve overrides. It's a bit wasteful to have to download toolchains again, but it's not user data. Overrides are user data and there should be a harder attempt to keep them.

**Comment by nodakai** [comment]
@kamalmarhubi Right, and this is probably why XDG standard distinguishes a config directory from a cache directory (cf. #247 )

**Comment by nathanaeljones** [comment]
In the meantime, perhaps tell users to kill the whole ~/.multirust directory?

https://github.com/rust-lang-nursery/rustup.rs/blob/a2e90aeeaadda81ef957b0829fbaddb5a730103a/src/rustup-cli/self_update.rs#L333

deleting only the version file isn't helpful. 

Maybe 

> warning: run `/usr/local/lib/rustlib/uninstall.sh` as root and delete `/home/n/.multirust/version` before installing rustup 

Should be: 

> warning: run `/usr/local/lib/rustlib/uninstall.sh` as root and delete `/home/n/.multirust` before installing rustup

**Comment by kinnison** [comment]
My gut feeling is that multirust is no longer an issue, so I'm going to close this.  If you still have interest in multirust and issues with updating to a modern rustup then please open a fresh issue to discuss them.
