### ISSUE TITLE
multirust itself and proxied commands occasionaly crash on Windows 10

### ISSUE THREAD

**Issue by NobbZ** [rust-lang/rustup.rs#34]
multirust executable as well as all proxied rust-executables do occasionally crash when run.

I fired up MSVS-Debugger to see from where that crash comes from. It is shown as 

```
Unhandled exception at 0x00007FF80F455AEB (ntdll.dll) in multirust-607yx6q5qo89cvgo_file.exe: 0xC0000005: Access violation writing location 0x0000000000000024.
```

This was after trying to update multirust via `multirust self update`.

Another one occured when trying to `cargo build` in a toyproject (same addresses but some other executable:

```
Unhandled exception at 0x00007FF80F455AEB (ntdll.dll) in cargo.exe: 0xC0000005: Access violation writing location 0x0000000000000024.
```

This especially annoying when this occurs during a build with a deep dependency tree and I have to restart the build on every 2nd or 3rd compiled dependency, or on a `cargo test` when I have to try it about 3 to 5 times before the actual tests are run.

I don't have such problems when using a rust from official installer.

**Comment by kinnison** [comment]
This issue has seen no action in over two years.  If it remains a problem with modern `rustup` then please open a fresh issue with fresh information.

Thanks,

D.
