### ISSUE TITLE
Capture rustc --version executions separately

### ISSUE THREAD

**Issue by peschkaj** [rust-lang/rustup.rs#368]
We can capture executions of `rustc --version` and use that to enhance telemetry so that we can see how each version of rust is performing.

**Comment by brson** [comment]
This is a good start.

During a core team meeting others expressed a desire to have the version attached to every rustc event. I still think executing rustc a second time for every one requested is probably not acceptable. Right now I'd probably just parse it out of the manifest, but we can still start with the simple thing of intercepting `rustc --version`.

**Comment by peschkaj** [comment]
Agreed - this is a lot easier than just about anything else we could do. Can't we just add the version to `rustc`'s STDERR? ;) What could possibly go wrong?

**Comment by tesuji** [comment]
@kinnison Does this issue exist anymore?

**Comment by kinnison** [comment]
Indeed not given we no longer do telemetry
