### ISSUE TITLE
https://www.rustup.rs/ should show links to installation methods for other OSes

### ISSUE THREAD

**Issue by casey** [rust-lang/rustup.rs#443]
Currently, the only installation method displayed by rustup.rs is that of the autodetected OS. It would be nice if it displayed links to other installation methods, so that if I'm on windows I still have a way to get to the installation instructions for linux, etc.

This came up because I was on a windows box installing rust in a guest VM. My browser was in windows, but I was looking for installation instructions for linux, and I was unable to get to them without inspecting the page source.

**Comment by brson** [comment]
There is a link labeled "other installation options". Maybe this is positioned in a place where people miss it. I've heard at least one other person say such.

**Comment by casey** [comment]
Yeah, I missed it at first. Also, it links to the github readme, but it would be nice if you could just see the instructions for different platforms.

**Comment by vdelau** [comment]
Just a +1 as I found this similarly confusing. I came from https://rust-lang.org/install.html. I would expect a link right below the big button.

See for example https://www.google.nl/chrome/browser/desktop/ or https://www.jetbrains.com/clion/download/

**Comment by vdelau** [comment]
This seems to no longer be an issue.
