### ISSUE TITLE
Add support for 'arm-none-eabi'

### ISSUE THREAD

**Issue by JayKickliter** [rust-lang/rustup.rs#464]
My coworkers and I are keen to use Rust on bare-metal ARM Cortex-M microcontrollers, but the current process of getting set up is too complicated to get everyone onboard. It would be a much easier sell if rustup could set up the toolchain and libcore (no standard library).

**Comment by vapor99** [comment]
I have the same intention of using it on bare ARM Cortex-M and have the same issue as above.

**Comment by japaric** [comment]
FWIW, I'm currently working on documenting how to set up a Rust development environment for bare metal programming ARM Cortex-M devices. I'm still drafting the process to go from zero to blinking an LED, but once it's done I'll push it to [this repository].

[this repository]: https://github.com/japaric/copper

After I'm done with that documentation, I'm going to propose [an RFC](https://github.com/rust-lang/rfcs) that will let `rustup` install a target specification file and `libcore` (plus other freestanding crates like `liballoc`) binaries with just e.g. `rustup target add cortex-m3`.

I'm going to postpone the automatic installation of a C toolchain (`arm-none-eabi-gcc`) to another RFC as that feature needs to be general enough to also handle other scenarios like installing an SDK for Android/iOS targets and I haven't thought about how that would work.

**Comment by toothbrush7777777** [comment]
@japaric Cool. I am in great need of this feature, but I don't understand (yet) the process of cross-compiling or the Rust set-up.

**Comment by vapor99** [comment]
@japaric Oh, that's fantastic!  I think that will really help a lot of people like myself that want to use Rust for embedded development.

**Comment by japaric** [comment]
@toothbrush7777777 

> Cool. I am in great need of this feature, but I don't understand (yet) the process of cross-compiling or the Rust set-up.

Might want to take a look at [rust-cross](https://github.com/japaric/rust-cross) to understand the requirements of cross compilation and how to cross compile with `rustc`/`cargo`.

> However, as far as I understand, there are several EABIs for ARM:

What devices do you have in mind? Those targets sound like you want to do bare metal programming of Cortex **A** processors like the Raspberry Pi. I'm not familiar with bare metal programming of those though.

If you actually meant targets like `arm-unknown-linux-gnueabi` and co (that run Linux) cross compiling to those is already supported by the compiler and relatively straightforward. See rust-cross.

> I personally need to target the big-endian versions of both arm-none-gnueabihf and aarch64-none-gnu

I think the big endian version of the `arm` target is `armeb-*-*`. I don't know what's the counterpart for the `aarch64` target. Supporting the big endian version of those targets may need changes in the standard libraries/libc crate. AFAIK no one has tried/reported cross compiling to those targets before.

@vapor99 

:smile: The docs I'm writing are aimed to people that haven't done embedded development before. My goal is to lower the entry barrier to this area of programming as much as possible. Using Rust instead of C is part of that goal but the tooling could be improved hence the RFC I mentioned above.

**Comment by toothbrush7777777** [comment]
@japaric Thanks, I'll take a look.

**Comment by JayKickliter** [comment]
It turns out this a lot easier that I thought. I discovered this fact when trying to build someone else's [project](https://github.com/thejpster/bare-metal-arm-rust). There's a `libcore` crate you can put in your [`Cargo.toml`](https://github.com/thejpster/bare-metal-arm-rust/blob/master/Cargo.toml#L15). Just to make sure, I completely wiped any trace of rust/rustup/cargo from my system and did the following:
```
$ curl https://sh.rustup.rs -sSf | sh
$ source ~/.cargo/env
$ git clone https://github.com/thejpster/bare-metal-arm-rust.git
$ cd bare-metal-arm-rust/
$ rustup override add nightly
$ rustup override set nightly
$ cargo build --target=lm4f120
    Updating git repository `https://github.com/hackndev/rust-libcore`
   Compiling rust-libcore v0.0.3 (https://github.com/hackndev/rust-libcore#44866049)
   Compiling bare-metal-arm-rust v0.2.2 (file:///Users/jay/Downloads/bare-metal-arm-rust)
   Compiling primer v0.2.0 (file:///Users/jay/Downloads/bare-metal-arm-rust/primer)
```

It's a good workaround in the meantime.

**Comment by japaric** [comment]
@JayKickliter 

> There's a libcore crate you can put in your Cargo.toml.

That works fine until you have to add dependencies from crates.io like e.g. [byteorder](https://crates.io/crates/byteorder) that don't depend on the `rust-libcore` crate. When you hit that wall, check out [xargo](https://github.com/japaric/xargo).

@toothbrush7777777 

(Didn't see you edited your post until now)

Those linux targets are currently supported. The RPi1 is the `arm-unknown-linux-gnueabi` (or the `hf` variant depending on whether its OS is using the hard float ABI or the soft one) target, and the RPi3 is the `aarch64-unknown-linux-gnu` target. Cross compiling to those targets is done the standard way as documented in rust-cross: install C cross toolchain, `rustup target add $TARGET`, set linker in `.cargo/config`, `cargo build --target $TARGET`.

You need big endian variants of those targets, right? We would have to decide how to handle conditional compilation between those two variants (little & big) before adding support for them in the compiler / standard libraries.

@toothbrush7777777 Can you point me to a linux distribution that provides releases for big endian ARM? Those would be helpful for testing.

**Comment by japaric** [comment]
> After I'm done with that documentation, I'm going to propose an RFC that will let rustup install a target specification file and libcore (plus other freestanding crates like liballoc) binaries with just e.g. rustup target add cortex-m3.

PSA: I have submitted [the RFC](https://github.com/rust-lang/rfcs/pull/1645).

**Comment by japaric** [comment]
> FWIW, I'm currently working on documenting how to set up a Rust development environment for bare metal programming ARM Cortex-M devices.

PSA: The [documentation](http://japaric.github.io/copper) is up now.

**Comment by vapor99** [comment]
Oh that's terrific, I will definitely check it out.  Nice work!

**Comment by fabricedesre** [comment]
Now that https://github.com/rust-lang/rust/pull/36874 landed would that be easier to add the new targets?

**Comment by japaric** [comment]
@fabricedesre The Rust/tooling team is leaning towards [*not* providing binary releases of the core crate](https://github.com/rust-lang/rfcs/pull/1645#issuecomment-248463998) as making [Cargo capable of (cross) compiling `core`/`std`](https://github.com/rust-lang/rfcs/pull/1133) would be a better solution. Right now, the stop gap solution is [Xargo](https://crates.io/crates/xargo) which cross compiles the core crate on the fly.

Installing the toolchain using rustup could be handled by [rustup plugin](https://github.com/rust-lang-nursery/rustup.rs/pull/655). An alternative to having rustup install the toolchain is to make rustc no longer depend on arm-none-eabi-gcc by [embedding lld, LLVM's linker, in rustc](https://github.com/rust-lang/rust/pull/36120); that internal lld would handle linking Rust programs.

**Comment by JasonKleban** [comment]
How can we use xargo to compile for bare metal RPi3?  https://stackoverflow.com/questions/51005145/cross-compiling-baremetal-rust-for-raspberry-pi-3-b-from-windows

**Comment by kinnison** [comment]
I believe appropriate targets now exist in Rust.
