### ISSUE TITLE
Idea: Automagically install "targets"?

### ISSUE THREAD

**Issue by japaric** [rust-lang/rustup.rs#799]
When you do:

```
$ cargo build --target arm-unknown-linux-gnueabi
```

You are not calling the "real" Cargo; you are actually calling rustup. Since we are already invoking rustup and rustup knows which target are installed and which ones are not, would it make sense to have rustup automatically install the target for you if it's missing?

So, instead of this:

```
$ cargo build --target arm-unknown-linux-gnueabi || echo :-(
   Compiling foo v0.1.0 (file:///home/japaric/tmp/foo)
error[E0463]: can't find crate for `std`

error: aborting due to previous error
:-(
```

You get this:

```
$ cargo build --target arm-unknown-linux-gnueabi && echo :-)
info: downloading component 'rust-std' for 'arm-unknown-linux-gnueabi'
info: installing component 'rust-std' for 'arm-unknown-linux-gnueabi'
   Compiling foo v0.1.0 (file:///home/japaric/tmp/foo)
:-)
```

Though I wonder how useful this feature would be in a post "std aware" Cargo world. Would Cargo compile std for you if it's not installed in that future?

**Comment by kinnison** [comment]
I'm intrigued by the idea but not sure how it'd interact with any functionality Cargo might have in this arena these days.  Also I don't want to teach `rustup` to parse Cargo's command line syntax which isn't really in our remit, so my inclination is to close this.  If you feel that there's still legs in the idea, please open a fresh issue in which we can discuss things further.
