### ISSUE TITLE
Change `CARGO_TARGET_DIR` based on toolchain

### ISSUE THREAD

**Issue by DanielKeep** [rust-lang/rustup.rs#86]
Switching between toolchains with Multirust causes a lot of cache thrashing as Cargo removes and recompiles artifacts.

It would be nice if there was an option to have Multirust's `cargo` proxy automatically redefine the `CARGO_TARGET_DIR` environment variable so that instead of every toolchain's Cargo trying to output to `$PKGDIR/target`, they instead output to `$PKGDIR/target/$TOOLCHAIN`.  This would make, for example, testing across multiple Rust versions and/or toolchains (_i.e._ GNU _vs._ MSVC) _much_ easier.

**Comment by brson** [comment]
Hm, I was afraid that would happen if we moved to a common `$CARGO_HOME`. Doing as you suggest is probably a good idea. cc @alexcrichton

**Comment by alexcrichton** [comment]
I don't think this is related to `CARGO_HOME`, the problem here is for `target`.

I personally hit this problem as well but I would also not want multirust to silently start changing *also* the `target` directory. Perhaps some config option somewhere, but I like the current behavior as it's predictable.

**Comment by DanielKeep** [comment]
I'd personally be content with a directory-specific override that let me switch this on.

**Comment by Diggsey** [comment]
To clarify, does this problem only occur for two different toolchains with the same target triple?

**Comment by DanielKeep** [comment]
@Diggsey Actually, at the moment I have a suite of toolchains going from `1.0.0` through `1.6.0`, plus the usual `stable`, `beta`, `nightly` which all have the same target *plus* a `nightly-x86_64-pc-windows-msvc` which targets 64-bit MSVC as opposed to 32-bit GNU.  Ideally, they'd *all* output to different locations for crates where I maintain compatibility for multiple versions or need to test multiple backends.

**Comment by DanielKeep** [comment]
Just a note: I ended up writing a script for running my Travis test matrices locally, and it basically does the above: for each toolchain, it overrides the target directory.  Works pretty well; no more exhaustive rebuilds!

(The above should not be misconstrued as me not wanting this feature in multirust, by the way, just noting that this approach does seem to work fine in practice.)

**Comment by brson** [comment]
rustup has global settings now. We might make this an option with `rustup set unique-target-dirs` or something, where the target dir gets the toolchain name.

But instead what if we did not override the target dir when using the `default` toolchain, but any time you use a non-default toolchain it would go into a unique directory. That would make the common case behave like stock cargo, and only configure things specially once you start doing more advanced things.

**Comment by DanielKeep** [comment]
That would work, but I'd still *prefer* an explicit option, on the basis that all the target dirs then have a uniform layout (`target/$TOOLCHAIN`), which is handy when dealing with automation.

**Comment by kinnison** [comment]
I believe that rustc and friends now cope with swapping toolchains and rebuilding without needing to remove/recompile all objects, so I'm closing this.
